import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  container: {
    width: '100%',
    // height: 70,
    alignItems: 'center',
    justifyContent: 'center',
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
  },
  progSection: {
    width: '80%',
    height: 62,
    // alignItems: 'center',
  },
  progressBarContainer: {
    width: '100%',
    height: 5,
    backgroundColor: '#ccd9ca',
    borderRadius: 2,
    position: 'relative',
  },
  progressBar: {
    width: '100%',
    height: '100%',
    borderRadius: 5,
    overflow: 'hidden',
  },
  progressBarFill: {
    width: '100%',
    height: '100%',
    backgroundColor: '#00a137',
    position: 'absolute',
    top: 0,
    left: 0,
  },
  progressBarFiller: {
    width: '100%',
    height: '40%',
    backgroundColor: '#c8e8bc',
    opacity: 0.6,
  },
  perRecord: {
    position: 'relative',
    top: 13,
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dottedView: {
    position: 'absolute',
    bottom: -1,
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  dotted: {
    color: '#4f544f',
    opacity: 0.3,
  },
  progressBarHandle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: '#fff',
    position: 'absolute',
    top: -10,
    zIndex: 10,
  },
  progressText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 20,
  },
  roundPercent: {
    display: 'flex',
    flexDirection: 'row',
    height: 65,
    width: 65,
    backgroundColor: '#ff9900',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 50,
  },
  reader: {
    width: '20%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  label: {
    fontSize: 12,
    color: '#4f544f',
  },
});
export default styles;
